# Generated by Django 5.1.7 on 2025-05-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailyproduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.groups'),
        ),
    ]
