# Generated by Django 5.1.7 on 2025-05-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_groups_worker_worker_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='app.groups'),
        ),
    ]
