# Generated by Django 5.1.7 on 2025-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_worker_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
    ]
