# Generated by Django 5.1.7 on 2025-05-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dailyproduction_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='amount_due',
        ),
    ]
