# Generated by Django 5.1.7 on 2025-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_dailyproduction_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
