# Generated by Django 5.1.7 on 2025-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_worker_is_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
